# Generated by Django 3.1.1 on 2020-12-20 03:47

import apps.appEnfermedades.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id_enfermedad', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('nombreEnfermedad', models.CharField(max_length=30)),
                ('tipoPatogeno', models.CharField(max_length=15)),
                ('enfermedad', models.CharField(max_length=1000)),
                ('control', models.CharField(max_length=1000)),
                ('medidas', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'enfermedad',
                'verbose_name_plural': 'enfermedades',
            },
        ),
        migrations.CreateModel(
            name='ImgValidacion',
            fields=[
                ('id_imagen', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to=apps.appEnfermedades.models.obtener_ruta_validacion)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEnfermedades.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImgMuestra',
            fields=[
                ('id_imagen', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField(default=None)),
                ('image', models.FileField(upload_to='ImgMuestra/')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEnfermedades.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImgEntrenamiento',
            fields=[
                ('id_imagen', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to=apps.appEnfermedades.models.obtener_ruta_entrenamiento)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEnfermedades.enfermedad')),
            ],
        ),
    ]
