# Generated by Django 3.1.1 on 2020-12-20 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appEnfermedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(upload_to='diagnosticos')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('enfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEnfermedades.enfermedad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'diagnostico',
                'verbose_name_plural': 'diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('clase', models.CharField(max_length=36)),
                ('valor', models.FloatField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDiagnostico.diagnostico')),
            ],
        ),
    ]
