"""
Django settings for sistemainteligentecañadeazucar project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+s(5ws3#q8trzh*i&ao^6p4!ndz7hj+qbmb*nuxv2wmh^b07ma'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#UTILIZAR EN SERVIDOR
#ALLOWED_HOSTS = ['sistemainteligente2020.pythonanywhere.com']

#UTILIZAR LOCAL
ALLOWED_HOSTS = []

TIME_ZONE='America/Mexico_City'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup',
    'apps.appUsuario',
    'apps.appPrincipal',
    'apps.appDiagnostico',
    'apps.appComunidad',
    'apps.appReportes',
    'apps.appEnfermedades',
    'apps.appReentrenamiento',
    'apps.appBitacora',
    'apps.appBiblioteca',
    'apps.appRespaldo',
    'dbbackup',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistemainteligentecañadeazucar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistemainteligentecañadeazucar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#UTILIZAR DE MANERA LOCAL 
DATABASES = {

        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bdsistemainteligente',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'localhost',
    }
}

#UTILIZAR EN SERVIDOR
#DATABASES = {
#        'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'sistemainteligen$bdsistemainteligente',
#        'USER':'sistemainteligen',
#        'PASSWORD':'tensorflowkeras',
#        'HOST':'sistemainteligente2020.mysql.pythonanywhere-services.com',
#    }
#}

#UTILIZAR EN SERVIDOR 
#DBBACKUP_CONNECTORS = {
#        'default': {
#        'USER': 'sistemainteligen',
#        'PASSWORD': 'tensorflowkeras',
#        'HOST': 'sistemainteligente2020.mysql.pythonanywhere-services.com'
#    }
#}

#DBBACKUP_CONNECTOR_MAPPING = {
#    'django.db.backends.mysql': 'dbbackup.db.mysql.MysqlDumpConnector',
#}

#CAMBIAR A SQLITE3
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}


DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(BASE_DIR,'backup')}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-eu'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'assets/static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    )

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

AUTH_USER_MODEL='appUsuario.User'