# Generated by Django 3.1.1 on 2020-12-20 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reentrenamiento',
            fields=[
                ('id_reentrenamiento', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('num_filtro1', models.IntegerField()),
                ('num_filtro2', models.IntegerField()),
                ('num_epocas', models.IntegerField()),
                ('funcion_activacion', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id_error', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('valor', models.FloatField()),
                ('epoca', models.IntegerField()),
                ('reentrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appReentrenamiento.reentrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=36)),
                ('nombre_enfermedad', models.CharField(max_length=40)),
                ('num_clase', models.IntegerField()),
                ('reentrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appReentrenamiento.reentrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id_calidad', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('valor', models.FloatField()),
                ('epoca', models.IntegerField()),
                ('reentrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appReentrenamiento.reentrenamiento')),
            ],
        ),
    ]
